api { 
    web_server: http://31.204.128.128:8080
    api_server: http://31.204.128.128:8008
    files_server: http://31.204.128.128:8081
    credentials {
        "access_key" = "NWC2N63JWUKZKPYZS3ZK"
        "secret_key"  = "YAlwjdwVbJ8papzDgZQdtrC6yNG04pKMghrWFxwf6qhBR12kj9"
    }
}
